import sys
import os
import json
import re
from datetime import datetime

"""
Danishgah Management System - Offline Google Sheets Attendance & Data Converter
Generates clean PostgreSQL / Supabase SQL INSERT queries from exported CSV or Excel files.
No data loss, handles wide matrix format (April - August) and tabs.
"""

MONTH_MAP = {
    'jan': 1, 'january': 1, 'feb': 2, 'february': 2, 'mar': 3, 'march': 3,
    'apr': 4, 'april': 4, 'may': 5, 'june': 6, 'jun': 6, 'jul': 7, 'july': 7,
    'aug': 8, 'august': 8, 'sep': 9, 'september': 9, 'oct': 10, 'october': 10,
    'nov': 11, 'november': 11, 'dec': 12, 'december': 12
}

def clean_status(val):
    if not val:
        return None
    s = str(val).strip().lower()
    if not s or s in ['-', 'n/a', 'null', 'off', 'sunday', 'holiday']:
        return None
    if s.startswith('p') or s in ['1', 'true', 'yes', 'y', '✓', 'v']:
        return 'Present'
    if s.startswith('a') or s in ['0', 'false', 'no', 'n', 'x', '✗']:
        return 'Absent'
    if s.startswith('l') or s in ['leave', 'sl', 'cl']:
        return 'Leave'
    return None

def parse_col_date(header_str, default_month=4, default_year=2025):
    s = str(header_str).strip()
    if not s:
        return None
    
    # Day number only like "1", "01", "31"
    if re.match(r'^\d{1,2}$', s):
        day = int(s)
        if 1 <= day <= 31:
            return f"{default_year:04d}-{default_month:02d}-{day:02d}"
            
    # Format YYYY-MM-DD
    if re.match(r'^\d{4}-\d{2}-\d{2}$', s):
        return s

    # Regex for "01-Apr" or "Apr 01"
    m = re.search(r'(\d{1,2})[-/\s]([a-zA-Z]{3,9})', s) or re.search(r'([a-zA-Z]{3,9})[-/\s](\d{1,2})', s)
    if m:
        g1, g2 = m.group(1), m.group(2)
        if g1.isdigit():
            day = int(g1)
            m_str = g2.lower()
        else:
            m_str = g1.lower()
            day = int(g2)
        month_num = MONTH_MAP.get(m_str) or MONTH_MAP.get(m_str[:3])
        if month_num and 1 <= day <= 31:
            return f"{default_year:04d}-{month_num:02d}-{day:02d}"

    return None

def generate_sql(csv_filepath, output_sql_path="import_attendance.sql"):
    import csv
    records = []
    
    with open(csv_filepath, 'r', encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        rows = list(reader)
        
    if not rows:
        print("CSV file is empty.")
        return

    headers = rows[0]
    
    # Find student name and class columns
    name_col = -1
    class_col = -1
    for idx, h in enumerate(headers):
        h_clean = h.strip().lower()
        if h_clean in ['student name', 'name', 'student', 'full name']:
            name_col = idx
        elif h_clean in ['class', 'grade', 'standard']:
            class_col = idx
            
    if name_col == -1:
        name_col = 0

    sql_statements = []
    for r_idx, row in enumerate(rows[1:], start=2):
        if not row or len(row) <= name_col:
            continue
        student_name = row[name_col].strip()
        if not student_name or student_name.lower().startswith('name') or student_name.lower().startswith('total'):
            continue

        student_class = row[class_col].strip() if class_col != -1 and len(row) > class_col else "Muntazir (3-4)"

        for c_idx, val in enumerate(row):
            if c_idx in [name_col, class_col]:
                continue
            h_str = headers[c_idx] if c_idx < len(headers) else ""
            date_str = parse_col_date(h_str)
            if date_str:
                st = clean_status(val)
                if st:
                    name_esc = student_name.replace("'", "''")
                    class_esc = student_class.replace("'", "''")
                    sql_statements.append(
                        f"INSERT INTO attendance (student_name, class, date, status) "
                        f"VALUES ('{name_esc}', '{class_esc}', '{date_str}', '{st}');"
                    )

    with open(output_sql_path, 'w', encoding='utf-8') as f:
        f.write("-- Attendance Data SQL Import Script\n")
        f.write("-- Generated by Danishgah Import Script\n\n")
        f.write("\n".join(sql_statements))
        
    print(f"Successfully generated {len(sql_statements)} SQL INSERT statements in '{output_sql_path}'.")

if __name__ == '__main__':
    if len(sys.argv) > 1:
        generate_sql(sys.argv[1])
    else:
        print("Usage: python import_sheet.py <path_to_exported_attendance.csv>")
